AWSTemplateFormatVersion: "2010-09-09"
Description: "Glue Week2"
Resources:
  roleglue:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
  MyDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "dbcrawler"
        Description: "TestDatabaseDescription"
        LocationUri: "s3://crawlertarget/csv/"
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "crawlertarget"
  MyCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "crawler"
      Role: !GetAtt roleglue.Arn
      DatabaseName: !Ref MyDatabase
      Targets:
        S3Targets:
          - Path: !Ref S3Bucket
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
  MyJob:
    Type: AWS::Glue::Job
    Properties:
      AllocatedCapacity: 2
      Command:
        Name: glueetl
        ScriptLocation: "s3://data-suddu/job_scripts/job.py"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      Name: cf-job
      Role: !GetAtt roleglue.Arn