AWSTemplateFormatVersion: "2010-09-09"
Description: "Glue Week2"
Resources:
  roleglue:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
  Database:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "dbcrawler"
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "crawlertarget"
  Crawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "CSVCrawler"
      Role: !GetAtt roleglue.Arn
      DatabaseName: !Ref Database
      Targets:
        S3Targets:
          - Path: "s3://crawlertarget/csv/"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
  CrawlerParquet:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "ParquetCrawler"
      Role: !GetAtt roleglue.Arn
      DatabaseName: !Ref Database
      Targets:
        S3Targets:
          - Path: "s3://crawlertarget/job-output/"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
  MyJob:
    Type: AWS::Glue::Job
    Properties:
      AllocatedCapacity: 2
      Command:
        Name: glueetl
        ScriptLocation: "s3://data-suddu/job_scripts/job.py"
        PythonVersion: '3'
      ExecutionProperty:
        MaxConcurrentRuns: 2
      Name: job
      Role: !GetAtt roleglue.Arn
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"